-- Get users who failed to login from the same IP address at least 5 times
select CLIENT_IP, REPORTED_CLIENT_TYPE, count(distinct USER_NAME) as UNIQUE_USER_COUNT, min(EVENT_TIMESTAMP) as FIRST_EVENT, max(EVENT_TIMESTAMP) as LAST_EVENT
from SNOWFLAKE.ACCOUNT_USAGE.LOGIN_HISTORY
where IS_SUCCESS = 'NO' and ERROR_MESSAGE in ('INCORRECT_USERNAME_PASSWORD', 'USER_LOCKED_TEMP') and FIRST_AUTHENTICATION_FACTOR='PASSWORD' and
      EVENT_TIMESTAMP >= DATEADD(HOUR, -24, CURRENT_TIMESTAMP())
group by 1,2
having UNIQUE_USER_COUNT >= 1
order by 3 desc;